networks:
  auth:

services:
  db:
    image: mysql:8.0-bookworm
    container_name: mysql-db
    env_file: .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - auth
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  # простой ping без пароля
      interval: 30s  # проверка каждые 30 секунд
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always

  migrate:
    image: migrate/migrate:latest
    container_name: migrate-db
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database",
      "mysql://${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}?multiStatements=true&parseTime=true&tls=${DB_TLS}",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth
    restart: on-failure:5  # Retry до 5 раз при ошибке

volumes:
  mysql-data:
