// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	UserID      int32
	TokenHash   string
	IsRefreshed bool
	CreatedAt   time.Time
	ExpiresAt   time.Time
	RevokedAt   sql.NullTime
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
}
