// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package query

import (
	"context"
	"database/sql"
	"time"
)

const checkUserByID = `-- name: CheckUserByID :one
SELECT COUNT(*) = 1 AS user_exists
FROM users
WHERE id = ?
`

func (q *Queries) CheckUserByID(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserByID, id)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (id, email, password_hash)
VALUES (?, ?, ?)
`

type CreateUserParams struct {
	ID           int32
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
}

const generateRefreshToken = `-- name: GenerateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES (?, ?, ?)
`

type GenerateRefreshTokenParams struct {
	UserID    int32
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) GenerateRefreshToken(ctx context.Context, arg GenerateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, generateRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT user_id, token_hash, is_refreshed, created_at, expires_at, revoked_at FROM refresh_tokens
WHERE user_id = ? AND token_hash = ?
LIMIT 1
`

type GetRefreshTokenParams struct {
	UserID    int32
	TokenHash string
}

func (q *Queries) GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, arg.UserID, arg.TokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.UserID,
		&i.TokenHash,
		&i.IsRefreshed,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash
FROM users
WHERE email = ?
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = ? AND token_hash = ?
`

type RevokeRefreshTokenParams struct {
	UserID    int32
	TokenHash string
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.UserID, arg.TokenHash)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :execresult
UPDATE users
SET password_hash = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           int32
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
}

const useValidRefreshToken = `-- name: UseValidRefreshToken :execresult
UPDATE refresh_tokens
SET is_refreshed = TRUE
WHERE user_id = ?
      AND token_hash = ?
      AND is_refreshed = FALSE
      AND expires_at > NOW()
`

type UseValidRefreshTokenParams struct {
	UserID    int32
	TokenHash string
}

func (q *Queries) UseValidRefreshToken(ctx context.Context, arg UseValidRefreshTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, useValidRefreshToken, arg.UserID, arg.TokenHash)
}
