// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AccountMembersRole string

const (
	AccountMembersRoleViewer AccountMembersRole = "viewer"
	AccountMembersRoleEditor AccountMembersRole = "editor"
	AccountMembersRoleAdmin  AccountMembersRole = "admin"
	AccountMembersRoleOwner  AccountMembersRole = "owner"
)

func (e *AccountMembersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountMembersRole(s)
	case string:
		*e = AccountMembersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountMembersRole: %T", src)
	}
	return nil
}

type NullAccountMembersRole struct {
	AccountMembersRole AccountMembersRole
	Valid              bool // Valid is true if AccountMembersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountMembersRole) Scan(value interface{}) error {
	if value == nil {
		ns.AccountMembersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountMembersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountMembersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountMembersRole), nil
}

type TransactionsPeriod string

const (
	TransactionsPeriodDay   TransactionsPeriod = "day"
	TransactionsPeriodWeek  TransactionsPeriod = "week"
	TransactionsPeriodMonth TransactionsPeriod = "month"
	TransactionsPeriodYear  TransactionsPeriod = "year"
)

func (e *TransactionsPeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsPeriod(s)
	case string:
		*e = TransactionsPeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsPeriod: %T", src)
	}
	return nil
}

type NullTransactionsPeriod struct {
	TransactionsPeriod TransactionsPeriod
	Valid              bool // Valid is true if TransactionsPeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionsPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionsPeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionsPeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionsPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionsPeriod), nil
}

type Account struct {
	ID          int32
	Name        string
	Description sql.NullString
	OwnerID     int32
}

type AccountMember struct {
	AccountID int32
	UserID    int32
	Role      AccountMembersRole
}

type Transaction struct {
	ID         int32
	AccountID  int32
	UserID     int32
	Title      string
	Amount     string
	OccurredAt time.Time
	Period     NullTransactionsPeriod
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
}
