// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type RefreshToken struct {
	ID          int32
	UserID      int32
	TokenHash   string
	IsRefreshed bool
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
}
