name: Move Issue to In Progress

on:
  create:
    branches:
      - '**'

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
      PROJECT_ID: "PVT_kwDODcMvQs4BDA_j"  
    steps:
      - name: Check branch pattern and extract issue number
        id: extract
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch name: $BRANCH_NAME"

          if echo "$BRANCH_NAME" | grep -Eq '^(feature|bugfix|chore|docs|refactor|test)/([0-9]+)'; then
            ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '[0-9]+')
            echo "Issue number extracted: $ISSUE_NUMBER"
            echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          else
            echo "Branch name does not match required pattern. Exiting."
            exit 1
          fi

